//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiloInventoryManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exception
    {
        public int ExceptionID { get; set; }
        public string Message { get; set; }
        public string StackTrace { get; set; }
        public System.DateTime DateOccurred { get; set; }
    }
}
